version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: ${DATABASE_PORT}
        DATABASE_NAME: ${DATABASE_NAME}
        URL_SERVER: ${URL_SERVER}
    image: app-image
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      URL_SERVER: ${URL_SERVER}
    networks:
      - internal-network
    volumes:
      - images_donation_volume:/data

networks:
  internal-network:
    external: true

volumes:
  images_donation_volume:
    external: true